apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ccc
  labels:
      name: ccc
spec:
  selector:
    matchLabels:
      app: ccc
  replicas: 1
  template:
    metadata:
      labels:
        app: ccc
    spec:
      containers:
      - name: ccc
        image: python
        command: ["/bin/bash"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        ports:
        - containerPort: 8080
